version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webapi:
    build:
      context: ./WebApi
    container_name: webapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=taskapp;Username=admin;Password=admin"
    depends_on:
      - postgres
    ports:
      - "5000:80"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"

volumes:
  postgres_data:
