services:
  postgres_task:
    image: postgres:15
    container_name: postgres_task
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webapi:
    build:
      context: ./webapi
      dockerfile: Dockerfile
    container_name: webapi
    restart: always
    ports:
      - "8088:8088"
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - webapi

volumes:
  postgres_data: