services:
  postgres_task:
    image: postgres:15
    container_name: postgres_task
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  thundersapp:
    image: ${DOCKER_REGISTRY-}thundersapp
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: Frontend
      dockerfile: Dockerfile

volumes:
  postgres_data: